name: Documentation request
description: Request documentation or tutorial information about a Symbiota-related topic
title: "[Doc Request]: "
labels: ["symbiota-docs"]
body:
  - type: markdown
    attributes: 
      value: | 
        Thanks for taking the time to fill out this documentation request!
  - type: textarea
    id: topic
    attributes:
      label: What tool, feature, or topic are you trying to learn about?
      description: Please describe the specific feature or page. Add URLs and screenshots, if appropriate.
    validations: 
      required: true
  - type: input
    id: type
    attributes:
      label: What kind of tutorial or documentation information would you like to see?
      description: You can suggest more than one type of material.
      placeholder: E.g., workflow document, description, Symbiota Docs page, video walkthrough, live webinar
    validations:
      required: true
