name: Auto Assign Newly Opened Issues To Symbiota Triage Project

on:
  issues:
    types: [opened, reopened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 2
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/BioKIC/projects/2'
        column_name: 'Organize'
        
    - name: Assign REOPENED issues to project 2
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: github.event.action == 'reopened'
      with:
        project: 'https://github.com/orgs/BioKIC/projects/2'
        column_name: 'Organize'
